<?php

$config = array(
             	'personas' => array(array(
                                	'field'=>'id',
                                	'label'=>'Id',
                                	'rules'=>'required|trim|xss_clean'
                                ),
								array(
                                	'field'=>'tipo_id',
                                	'label'=>'Tipo_id',
                                	'rules'=>'required|trim|xss_clean'
                                ),
								array(
                                	'field'=>'nombre1',
                                	'label'=>'Nombre1',
                                	'rules'=>'required|trim|xss_clean'
                                ),
								array(
                                	'field'=>'nombre2',
                                	'label'=>'Nombre2',
                                	'rules'=>'trim|xss_clean'
                                ),
								array(
                                	'field'=>'apellido1',
                                	'label'=>'Apellido1',
                                	'rules'=>'required|trim|xss_clean'
                                ),
								array(
                                	'field'=>'apellido2',
                                	'label'=>'Apellido2',
                                	'rules'=>'trim|xss_clean'
                                ),
								array(
                                	'field'=>'celular',
                                	'label'=>'Celular',
                                	'rules'=>'required|trim|xss_clean'
                                ),
								array(
                                	'field'=>'fijo',
                                	'label'=>'Fijo',
                                	'rules'=>'trim|xss_clean'
                                ),
								array(
                                	'field'=>'email',
                                	'label'=>'Email',
                                	'rules'=>'trim|valid_email|xss_clean'
                                ),
								array(
                                	'field'=>'direccion',
                                	'label'=>'Direccion',
                                	'rules'=>'required|trim|xss_clean'
                                ),
								array(
                                	'field'=>'departamento_residencia',
                                	'label'=>'Departamento_residencia',
                                	'rules'=>'required|trim|xss_clean'
                                ),
								array(
                                	'field'=>'municipio_residencia',
                                	'label'=>'Municipio_residencia',
                                	'rules'=>'required|trim|xss_clean'
                                ),
								array(
                                	'field'=>'localidad',
                                	'label'=>'Localidad',
                                	'rules'=>'required|trim|xss_clean'
                                ),
								array(
                                	'field'=>'departamento_nacimiento',
                                	'label'=>'Departamento_nacimiento',
                                	'rules'=>'required|trim|xss_clean'
                                ),
								array(
                                	'field'=>'municipio_nacimiento',
                                	'label'=>'Municipio_nacimiento',
                                	'rules'=>'required|trim|xss_clean'
                                ),
								array(
                                	'field'=>'fecha_nacimiento',
                                	'label'=>'Fecha_nacimiento',
                                	'rules'=>'required|trim|xss_clean'
                                ),
								array(
                                	'field'=>'fecha_registro',
                                	'label'=>'Fecha_registro',
                                	'rules'=>'required|trim|xss_clean'
                                ))
			   );
			   
?>